#!/usr/bin/env python3
"""Generate one Coq source-definition file from one .js input."""

from __future__ import annotations

import pathlib
import re
import sys


def stem_to_definition_name(source_path: pathlib.Path) -> str:
    stem = re.sub(r"[^A-Za-z0-9_]", "_", source_path.stem)
    return f"{stem}_source"


def coq_string_literal(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '""')
    return f'"{escaped}"'


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: js_to_coq_source.py IN_JS OUT_V", file=sys.stderr)
        return 2

    source_path = pathlib.Path(argv[1])
    out_path = pathlib.Path(argv[2])
    definition_name = stem_to_definition_name(source_path)
    text = source_path.read_text(encoding="utf-8")

    lines = [
        "From Coq Require Import Strings.String.",
        "",
        "(* Generated by theories/jessie/tools/js_to_coq_source.py.",
        f"   Source: {source_path.as_posix()}.",
        "   Edit the .js file, not this generated Coq file. *)",
        "",
        "Open Scope string_scope.",
        "",
        f"Definition {definition_name} : string :=",
        f"  {coq_string_literal(text)}.",
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
